### ISSUE TITLE
Fix the package not found issue

### ISSUE THREAD

**Issue by Seniru** [csstools/postcss-trig#2]
In the README file the npm badge states 'Not found'. Also I can't find the respective page for this package in npm page.

Could anybody fix this problem?

**Comment by Antonio-Laguna** [comment]
@Seniru this plugin is no longer maintained but we have released this one: https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-trigonometric-functions which only tackles Trigonometric functions.

Sorry this took so long!
